[package]

name = "todo-backend-rust"
version = "0.1.0"
authors = [ "jack@jacksingleton.com" ]

[dependencies.iron]
git = "https://github.com/iron/iron.git"

[dependencies.uuid]
git = "https://github.com/rust-lang/uuid.git"
